import {getPair } from "../homework4/main.js";
import { getRandomArray } from "../homework5/main.js";
import {students, getAvarageMark } from "../homework6/main.js";
import { ukraine, latvia, litva, getMySalary } from "../homework7/main.js";
import { Student } from "../homework8/class.js";
import { getRandomColor, generateBlocks } from "../homework9/main.js";
import { playSound } from "../homework10/main.js";
import { getRandomChinese } from "../homework11/main.js";
import { getPeople } from "../homework12/newMain.js";
import { createIdGenerator } from "../homework13/main.js";